spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbs:postgresql://localhost:5432/postgres
    username: postgres
    password: 2000
  flyway:
    baseline-on-migrate: true

