spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbs:postgresql://localhost:5432/shop
    username: postgres
    password: 2000
  flyway:
    baseline-on-migrate: true

